spring:
  application:
    name: consulta-medica
  datasource:
    url: jdbc:h2:mem:consulta-medica
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  #  jpa:
  #    show-sql: true
  #    open-in-view: false
  #    hibernate:
  #      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2-console